### ISSUE TITLE
Border When TextBox Focused

### ISSUE THREAD

**Issue by haleemzahid** [bilalkhan009/signup-form-repo#1]
Steps to see the issue

1. Open the xevenskill.html file
2. Click on username input. You will see that the square border is shown which needs to be removed. See the attached
![image](https://user-images.githubusercontent.com/16895707/231207633-2639ffac-f7ae-4eba-8f1c-a8e6785b6151.png)

**Comment by bilalkhan009** [comment]
the 1st isue not understand 

-> I don't understand what you mean. Could you please explain this issue in details?

**Comment by haleemzahid** [comment]
As you can see the textbox has border when you click on it. Which I dont want.
At first it has only border bottom, but when tou click on it and then the border appear for all sides which i dont want

**Comment by bilalkhan009** [comment]
okay this border remove from the text box?
